=== daiedaie/funds/mrbt_funds_manage/src/main/java/com/mrbt/utils/freemaker/xml/xml_bean.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="path">
		<xs:complexType>
			<xs:attribute name="vist-url" use="required" />
			<xs:attribute name="jsp" use="required" type="xs:anyURI"/>
			<xs:attribute name="js" use="required" type="xs:anyURI"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="title">
	</xs:element>
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="TypeCombo" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="entry">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="string"/>
				<xs:element ref="list"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="comboMaps">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="entry" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="columns">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="column" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="column">
		<xs:complexType>
			<xs:attribute name="id" type="xs:boolean" use="optional"/>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="type" use="optional" default="string">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="hidden"/>
						<xs:enumeration value="string"/>
						<xs:enumeration value="int"/>
						<xs:enumeration value="date"/>
						<xs:enumeration value="time"/>
						<xs:enumeration value="combobox"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="format" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="date"/>
						<xs:enumeration value="combobox"/>
						<xs:enumeration value="time"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="label" type="xs:string" use="required"/>
			<xs:attribute name="search" type="xs:boolean" use="optional"/>
			<xs:attribute name="save" type="xs:boolean" use="optional"/>
			<xs:attribute name="grid" type="xs:boolean" use="optional"/>
			<xs:attribute name="view" type="xs:boolean" use="optional"/>
			<xs:attribute name="update" type="xs:boolean" use="optional"/>
			<xs:attribute name="comboName" type="xs:string" use="optional"/>
			<xs:attribute name="width" type="xs:int" use="optional" default="200"/>
			<xs:attribute name="labelWidth" type="xs:int" use="optional" default="200"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="bean">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="path"/>
				<xs:element ref="title"/>
				<xs:element ref="comboMaps"/>
				<xs:element ref="columns"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="TypeCombo">
		<xs:complexType>
			<xs:attribute name="text" type="xs:string" use="required"/>
			<xs:attribute name="option" type="xs:int" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="string"/>
</xs:schema>

=== daiedaie/funds/mrbt_funds_manage/src/main/java/com/mrbt/utils/freemaker/xml/company/depart.xml
<?xml version="1.0" encoding="UTF-8"?>
<bean xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
      xsi:noNamespaceSchemaLocation="../xml_bean.xsd">
	<path jsp="E:/project/mrbt/mrbt_oa/WebContent/WEB-INF/jsp/company/depart" 
	js="E:/project/mrbt/mrbt_oa/WebContent/resource/js/company/depart"
	vist-url="/rest/company/depart" />
	<title>权限管理</title>
	<comboMaps>
		<entry>
			<string>dp_status</string>
			<list>
				<TypeCombo option="0" text="有效"/>
				<TypeCombo option="1" text="无效"/>
			</list>
		</entry>
	</comboMaps>
	<columns>
		<column name="id" label="id" id="true"/>
		<column  name="dpName" type="string" search="true" label="部门名称"></column>
		<column  name="dpStatus" format="combobox" type="combobox" label="部门状态" comboName="dp_status" ></column>
	</columns>
</bean>

=== daiedaie/funds/mrbt_funds_manage/src/main/java/com/mrbt/utils/freemaker/xml/company/user.xml
<?xml version="1.0" encoding="UTF-8"?>
<bean  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
      xsi:noNamespaceSchemaLocation="../xml_bean.xsd">
	<path jsp="E:/project/mrbt/mrbt_oa/WebContent/WEB-INF/jsp/company/user" 
	js="E:/project/mrbt/mrbt_oa/WebContent/resource/js/company/user"
	vist-url="/rest/company/user" />
	<title>员工登录账户管理</title>
	<comboMaps>
		<entry>
			<string>state</string>
			<list>
				<TypeCombo option="0" text="正常"/>
				<TypeCombo option="1" text="暂停"/>
				<TypeCombo option="2" text="删除"/>
			</list>
		</entry>
	</comboMaps>
	<columns>
		<column  id="true" name="id" label="id" ></column>
		<column  name="loginName" type="string" search="true" label="登录名称"></column>
		<column  name="loginPass" type="string" label="" grid="false" save="false" update="false" view="false"></column>
		<column  name="loginStatus" format="combobox" type="combobox" label="状态" comboName="state" ></column>
		<column  name="lastDt" type="date" format="date" label="最后登录时间" save="false" update="false"></column>
		<column  name="lastIp" type="string" label="最后登录ip" save="false" update="false"></column>
	</columns>
</bean>

=== daiedaie/funds/mrbt_funds_manage/src/main/java/com/mrbt/utils/freemaker/xml/company/role.xml
<?xml version="1.0" encoding="UTF-8"?>
<bean xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
      xsi:noNamespaceSchemaLocation="../xml_bean.xsd">
	<path jsp="E:/project/mrbt/mrbt_oa/WebContent/WEB-INF/jsp/company/role" 
	js="E:/project/mrbt/mrbt_oa/WebContent/resource/js/company/role"
	vist-url="/rest/company/role" />
	<title>权限管理</title>
	<comboMaps>
		<entry>
			<string>r_status</string>
			<list>
				<TypeCombo option="0" text="有效"/>
				<TypeCombo option="1" text="无效"/>
			</list>
		</entry>
	</comboMaps>
	<columns>
		<column name="id" label="" id="true"/>
		<column  name="rName" type="string" search="true" label="权限名称"></column>
		<column  name="description" type="string" label="描述信息"></column>
		<column  name="rStatus" format="combobox" type="combobox" label="角色状态" comboName="r_status" ></column>
	</columns>
</bean>
